#!/bin/bash 

REFDIR=$1
TAG=$2
GTF=$3
FA=$4

if [[ $# != 4 ]]
then 
  echo "USAGE: prepare_eukaryotic_reference <ref_directory> <tag> <gtf> <fa>"
  exit 1
fi 

## we create directory $REFDIR/$TAG, and put all the necessary reference files and dirs there. 

## 1) process GTF and learn what's up with different tags - maybe automate this? 
## 2) if there are PAR genes, lose them 
## 3) generate STAR reference 
## 4) generate RSEM ref and transcripts 
## 5) generate kallisto ref using transcript sequences from RSEM 
## 6) make .3col and .4col files for tables 
## 7) trickiest part: make rRNA interval and refFlat files for Picard (daym this be some dumb shit). 
