#!/bin/bash 

REFDIR=$1
SPECIES=$2 ## e.g. genprime_vM12
CPUS=$3
WDIR=`pwd`

GRN='\033[1;32m'
GRN2='\033[0;32m'
UL='\033[4;34m'
NC='\033[0m' # No Color

if [[ $# != "3" ]]
then
  echo "=================================================================================="
  echo "=================================================================================="
  echo "===                                                                            ==="
  printf "===              ${GRN2}What is the airspeed velocity of an unladen swallow?${NC}          ===\n"
  echo "===                                                                            ==="
  printf "===                  USAGE: ${GRN}rnaquant${NC} ${GRN2}<ref_dir> <tag> <CPUs>${NC}                    ===\n" 
  printf "===   For more usage information, visit ${UL}https://github.com/apredeus/rnaquant${NC}   ===\n"
  echo "===                                                                            ==="
  echo "=================================================================================="
  echo "=================================================================================="
  exit 1
fi

cd $WDIR

echo "=================================================================================="
echo "=================================================================================="
echo "===                                                                            ==="
echo "===                             Welcome to RNAQUANT!                           ==="
echo "===  For more information, please visit https://github.com/apredeus/rnaquant   ==="
echo "===                          Publication in preparation.                       ==="
echo "===                                                                            ==="
echo "=================================================================================="
echo "=================================================================================="
echo
echo

if [[ -d fastqs && "$(ls -A fastqs)" ]]; then
  echo "Found non-empty directory named fastqs! Continuing."
else
  echo "ERROR: directory fastqs does not exist and is empty!"
  exit 1
fi

if [[ ! -d bams || ! -d picard_stats || ! -d tdfs_and_bws || \
! -d RSEM || ! -d featureCounts || ! -d FastQC || ! -d STAR_logs || \
! -d kallisto || ! -d exp_tables || ! -d tr_bams ]]
then
  echo "One of the required directories is missing, I will try to create them."
  mkdir bams picard_stats tdfs_and_bws RSEM featureCounts FastQC kallisto exp_tables STAR_logs tr_bams
else
  echo "All the necessary directories found, continuing." 
fi

if [[ $SPECIES == "" || $REFDIR == "" ]]
then
  echo "ERROR: You have to specify REFDIR and SPECIES!"
  exit 1
fi

if [[ $CPUS == "" ]]
	then 
  echo "Parallel jobs have been set to default - running on 4 cores."
  CPUS=4
else 
  echo "Parallel jobs will be ran on $CPUS cores."
fi

SDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo "Found rnaquant executable in directory $SDIR"

echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 1: Running FastQC.."
#cd $WDIR/fastqs 
#$SDIR/script/parallel_fastqc.sh $WDIR $CPUS
echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 2: Running STAR genome and transcriptome alignment.."
#cd $WDIR/fastqs
#$SDIR/script/parallel_star_align.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS
echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 3: Making TDF and strand-specific bigWig files.."
#cd $WDIR/bams
#$SDIR/script/parallel_calculate_coverage.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS
echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 4: Running featureCounts on all possible strand settings.."
#cd $WDIR/bams
#$SDIR/script/parallel_strand_quant.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS
echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 5: Calculating strandedness from featureCounts.."
#cd $WDIR/fastqs
#$SDIR/script/parallel_calculate_stats.sh $SDIR $WDIR
echo 
echo "=================================================================================="
echo

#echo "["`date +%H:%M:%S`"] Step 6: Calculating strandedness and other stats using Picard tools.."
#cd $WDIR/picard_stats
#$SDIR/script/parallel_picard_stats.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS
echo 
echo "=================================================================================="
echo

cd $WDIR/picard_stats
STRANDP=`grep PCT_CORRECT_STRAND_READS -A 1 *.picard.metrics | awk -F "\t" '{print $23}' | grep -v -P "^$|PCT_CORRECT_STRAND_READS" | awk '{sum+=$1} END {printf "%.2f\n",sum*100/NR}'`
echo "Strandedness estimates: $STRANDP (Picard tools)."

cd $WDIR/featureCounts 
cat *strand | awk 'BEGIN {min=100;max=0} {sum+=$16; if($16>max) \
{max=$16}; if($16<min) {min=$16};} END {print "featureCounts: average percent of \
reads matching the coding strand: "sum/NR", lowest: "min", highest: "max}'

STRAND=`cat *strand | awk '{sum+=$16} END {x=sum/NR; if (x<10) \
{print "RF"} else if (x>90) {print "FR"} else if (x>45 && x<55) \
{print "NONE"} else {print "ERROR"}}'`

if [[ $STRAND == "ERROR" ]]
then
  echo "ERROR: something is very much off with the strand-specificity of your RNA-seq!"
  echo "       This means that average strand-specificity of the dataset does not fall into"
  echo "       one of the following intervals: [0%,10%), (45%,55%), or (90%,100%]."
  echo "       This is very irregular; please investigate why is this happening using contents"
  echo "       of <wdir>/strand and <wdir>/stats directories." 
  exit 1
else
  echo "The strandedness of your experiment was determined to be $STRAND"
fi
cd ..

#echo "["`date +%H:%M:%S`"] Step 7: Running kallisto abundance estimation.."
#cd $WDIR/fastqs
#$SDIR/script/parallel_kallisto_quant.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS $STRAND
echo 
echo "=================================================================================="
echo

echo "["`date +%H:%M:%S`"] Step 8: Running RSEM abundance estimation.."
cd $WDIR/tr_bams
$SDIR/script/parallel_rsem_quant.sh $SDIR $WDIR $REFDIR $SPECIES $CPUS $STRAND
echo 
echo "=================================================================================="
echo

echo "["`date +%H:%M:%S`"] Step 9: Making final expression tables.."
cd $WDIR/featureCounts
$SDIR/script/make_tables.sh $WDIR $REFDIR $SPECIES 
echo 
echo "=================================================================================="
echo

echo "["`date +%H:%M:%S`"] RNA-Seq processing is done! Final expression tables are available in exp_tables."
echo "["`date +%H:%M:%S`"] ALL YOUR BASES ARE BELONG TO US!"
